In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/python/3.14.2/lib/python3.14/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# full(taille, value)
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2]

np.int64(3)

In [8]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
 np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dementional arrays

In [19]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [34]:
n[:,2]

array([3, 6, 9])

In [ ]:
# Ra

In [40]:
np.random.seed(2)
100*np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [39]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [42]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2)) # 100 est exclu

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Comparison operations

In [13]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [14]:
a*100

array([  0, 100, 200, 300, 400])

In [15]:
b = (10 + (a*2))**2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [16]:
a+b # >

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [17]:
a > b

array([False, False,  True,  True,  True])

In [18]:
a >= b

array([False, False,  True,  True,  True])

In [19]:
a[a>b]

array([2, 3, 4])

# Summarizing operations

In [21]:
a

array([0, 1, 2, 3, 4])

In [22]:
a.min() # Minimum

np.int64(0)

In [23]:
a.max() # Maximum

np.int64(4)

In [24]:
a.sum() # Somme

np.int64(10)

In [25]:
a.mean() # Moyenne

np.float64(2.0)

In [26]:
a.std() # Ecart type

np.float64(1.4142135623730951)